# Generated by Django 4.2.23 on 2025-07-04 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is soft deleted",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about the bookmark",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for organizing bookmarks",
                        max_length=255,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this bookmark is private to the user",
                        verbose_name="Is Private",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmark",
                "verbose_name_plural": "Bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookmarkCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is soft deleted",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the collection",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the collection",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this collection is publicly visible",
                        verbose_name="Is Public",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex color code for the collection",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmark Collection",
                "verbose_name_plural": "Bookmark Collections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookmarkCollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the bookmark in the collection",
                        verbose_name="Order",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the bookmark was added to the collection",
                        verbose_name="Added At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmark Collection Item",
                "verbose_name_plural": "Bookmark Collection Items",
                "ordering": ["order", "added_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is soft deleted",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        help_text="Primary language of the content",
                        max_length=7,
                        verbose_name="Language",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the title",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description for search engines (max 160 characters)",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for search engines",
                        max_length=255,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for display purposes",
                        verbose_name="Order",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        help_text="Arabic name of the category",
                        max_length=100,
                        unique=True,
                        verbose_name="Arabic Name",
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        blank=True,
                        help_text="Arabic description of the category",
                        verbose_name="Arabic Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="CSS icon class for the category",
                        max_length=50,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "post_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of posts in this category",
                        verbose_name="Post Count",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is soft deleted",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        help_text="Primary language of the content",
                        max_length=7,
                        verbose_name="Language",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the title",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description for search engines (max 160 characters)",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for search engines",
                        max_length=255,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for display purposes",
                        verbose_name="Order",
                    ),
                ),
                (
                    "post_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of posts using this hashtag",
                        verbose_name="Post Count",
                    ),
                ),
                (
                    "is_trending",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this hashtag is currently trending",
                        verbose_name="Is Trending",
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this hashtag was last used",
                        verbose_name="Last Used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hashtag",
                "verbose_name_plural": "Hashtags",
                "ordering": ["-post_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is soft deleted",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Arabic Title"
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "content_ar",
                    models.TextField(blank=True, verbose_name="Arabic Content"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Summary")),
                (
                    "summary_ar",
                    models.TextField(blank=True, verbose_name="Arabic Summary"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="View Count"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta Description"),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta Keywords"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is soft deleted",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="Arabic Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Arabic Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
            ],
            options={
                "verbose_name": "Post Type",
                "verbose_name_plural": "Post Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is soft deleted",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        help_text="Primary language of the content",
                        max_length=7,
                        verbose_name="Language",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the title",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description for search engines (max 160 characters)",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for search engines",
                        max_length=255,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for display purposes",
                        verbose_name="Order",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        help_text="Arabic name of the sub-category",
                        max_length=100,
                        verbose_name="Arabic Name",
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        blank=True,
                        help_text="Arabic description of the sub-category",
                        verbose_name="Arabic Description",
                    ),
                ),
                (
                    "post_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of posts in this sub-category",
                        verbose_name="Post Count",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Parent category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="content.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PostSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.post"
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Sub Category",
                "verbose_name_plural": "Post Sub Categories",
            },
        ),
        migrations.CreateModel(
            name="PostHashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hashtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.hashtag",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.post"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post HashTag",
                "verbose_name_plural": "Post HashTags",
            },
        ),
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.category",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.post"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Category",
                "verbose_name_plural": "Post Categories",
            },
        ),
        migrations.CreateModel(
            name="PostAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is soft deleted",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="post_attachments/%Y/%m/%d/", verbose_name="File"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="File Type"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="File Size"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="content.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Attachment",
                "verbose_name_plural": "Post Attachments",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
