# Generated by Django 4.2.23 on 2025-07-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postattachment",
            name="download_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this attachment has been downloaded",
                verbose_name="Download Count",
            ),
        ),
        migrations.AddField(
            model_name="postattachment",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Whether this attachment is publicly visible",
                verbose_name="Is Public",
            ),
        ),
    ]
