# Generated by Django 4.2.23 on 2025-07-29 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0002_department"),
        ("content", "0003_postattachment_download_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="producers.department",
                verbose_name="Department",
            ),
        ),
    ]
