# Generated by Django 4.2.23 on 2025-08-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_post_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
    ]
