# Generated by Django 4.2.23 on 2025-08-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postattachment",
            name="file",
            field=models.FileField(
                max_length=500,
                upload_to="post_attachments/%Y/%m/%d/",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Title"),
        ),
    ]
