# Generated by Django 4.2.23 on 2025-08-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_increase_attachment_field_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postattachment",
            name="file_type",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="File Type"
            ),
        ),
    ]
