# Generated by Django 4.2.23 on 2025-07-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("code", models.CharField(max_length=10, verbose_name="City Code")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["state", "name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 country code",
                        max_length=3,
                        unique=True,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("code", models.CharField(max_length=10, verbose_name="State Code")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="geographics.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "ordering": ["country", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(fields=["code"], name="geographics_code_9bab97_idx"),
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="geographics.state",
                verbose_name="State",
            ),
        ),
        migrations.AddIndex(
            model_name="state",
            index=models.Index(
                fields=["country", "code"], name="geographics_country_8f6fe4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together={("country", "code")},
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["state", "code"], name="geographics_state_i_c29c3d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("state", "code")},
        ),
    ]
