# Generated by Django 4.2.23 on 2025-07-29 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_ar",
                    models.CharField(max_length=255, verbose_name="Arabic Name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Department Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Arabic Description"),
                ),
                (
                    "head_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Department Head Name"
                    ),
                ),
                (
                    "head_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Department Head Email"
                    ),
                ),
                (
                    "head_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Department Head Phone"
                    ),
                ),
                (
                    "employee_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Employees"
                    ),
                ),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("admin", "Administrative"),
                            ("media", "Media"),
                            ("technical", "Technical"),
                            ("financial", "Financial"),
                            ("legal", "Legal"),
                            ("hr", "Human Resources"),
                            ("it", "Information Technology"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Department Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "subsidiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="producers.subsidiary",
                        verbose_name="Subsidiary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["subsidiary", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="producers_d_code_b609ac_idx"),
                    models.Index(
                        fields=["is_active"], name="producers_d_is_acti_77ce17_idx"
                    ),
                    models.Index(
                        fields=["department_type"],
                        name="producers_d_departm_00f304_idx",
                    ),
                ],
                "unique_together": {("subsidiary", "code")},
            },
        ),
    ]
