# Generated by Django 4.2.23 on 2025-07-29 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="userinterest",
            options={
                "ordering": ["name"],
                "verbose_name": "User Interest",
                "verbose_name_plural": "User Interests",
            },
        ),
    ]
