# Generated by Django 4.2.23 on 2025-07-29 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_alter_userinterest_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollowing",
        ),
    ]
